### ISSUE TITLE
Data DEX UI cleanup before mainnet

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#627]
- [x] Add get whitelisted page so it's accessible from somewhere - please input @newbreedofgeek 
- [x] Home icon from navbar should take user to home, not to dashboard
- [x] Advertise data card on trade data page does not have margin on bottom (mobile)
- [x] Advertise data card on trade data page not centered (mobile)
- [x] Skeleton loading on wallet is not centered (check both desktop and mobile)
- [x] Skeleton loading in marketplace is not centered (check both desktop and mobile)
- [x] Purchase data not working from details page #618 
- [x] Discord link in get whitelisted page #611 
- [x] Telegram link in get whitelisted page #611 
- [x] Error messages overlapping helper text in Data NFT minting drawer #465 
- [x] The part before Recent Data NFTs is not centered on deashboard (mobile)
- [x] Update MX libraries (merge my PR)
- [x] in the Minter Form, if we detect the person is NOT whitelisted - then the whole form is blurred out (like an overlay that blurs it similar to when a “Data NFT is frozen” - in the middle of the blurred out box, there is a call to action button that says.. “find out how you can get whitelisted” - when user clicks this it goes to the get whitelisted in the same browser window
- [x]  in the homepage we can have a button (next to Market) in the header for “Get Whitelisted ” - that goes to the stand alone page (only when not logged in)
- [x] Change Lorem Ipsum text

- [x] WHEN ALL ELSE DONE, final check to see: all buttons work, all transactions work for all types of wallets

@newbreedofgeek and @fuzzyduke , please expand this list if you see I missed anything

**Comment by fuzzyduke** [comment]
Advertise data card doesn't show "Advertise Data" button. This is seen after "Load Test Data" is invoked from the dashboard.

![image](https://github.com/Itheum/data-dex/assets/121969933/645ec4cf-9192-4e3d-8da5-6b6b91b01f97)

![image](https://github.com/Itheum/data-dex/assets/121969933/c01264b8-628c-4e21-b2dd-b012d2647d10)

**Comment by damienen** [comment]
@fuzzyduke i also solved the thing you noticed

**Comment by fuzzyduke** [comment]
"Public Marketplace" and "My Listed Data NFTs" in mobile view are skewed. UI Modification is required to properly see both tabs.

![image](https://github.com/Itheum/data-dex/assets/121969933/f01edcb2-2e38-414a-883f-2a0bfbcfdfb6)

**Comment by damienen** [comment]
@fuzzyduke you can scroll laterally to see them both.

Yes, not ideal, but until we get a new UI possibility to do it, we will roll this way

**Comment by fuzzyduke** [comment]
Okay. Kindly confirm the view below "Your Data NFT(s)" is one below the other on 3 lines, as the text is short can we make this in 2 lines?

![image](https://github.com/Itheum/data-dex/assets/121969933/26e81599-9747-4a2a-bdfc-8e1f85456689)

**Comment by damienen** [comment]
I'll look into it. Not worth putting a lot of effort into it as we will
change that whole design on mobile very soon and it looks reasonably ok
now, but yes, would be better to have them on 2 rows.

**Comment by fuzzyduke** [comment]
Apart from skeleton being centered as per earlier comments, kindly note that in the wallet and marketplace, the height and width of the skeleton from the original card still differ.

**Comment by fuzzyduke** [comment]
User is able to acquire their own NFT in the marketplace in detail view in both marketplace sections "Public Marketplace" and "My Listed Data NFTs"

Remove the purchase button in the detail view for the user who has listed the Data NFT.

![image](https://github.com/Itheum/data-dex/assets/121969933/ef33e828-499a-4ffa-a418-1eccd01ea74f)

**Comment by damienen** [comment]
Solved the last one, too, @fuzzyduke

**Comment by BogdanCostinas** [comment]
1. There are some fields that are not marked as Mandatory, refine the form and make it all Mandatory ( Could add N/A ) if they do not own accounts in there ( eg. Twitter, telegram etc ) 

2. Where do you collect data to be rephrased into "What format is the data that you collect"

![image](https://github.com/Itheum/data-dex/assets/118804443/bf3fe8c8-a40b-4349-bd4c-879e08172bf9)

**Comment by BogdanCostinas** [comment]
Web Wallet connection - do not display the tokens holdings/ Claims portal tokens also not displayed

![image](https://github.com/Itheum/data-dex/assets/118804443/256735ce-5cca-40ab-9e79-534bf3c5c9c0)

**Comment by BogdanCostinas** [comment]
Web Wallet- Sign The message to view data - Still error and right after the error you get logged out

**Comment by BogdanCostinas** [comment]
When you want to list multiple Data NFTs, right before signing the message, the UI quickly changes to " List 1 instead of xx"


https://github.com/Itheum/data-dex/assets/118804443/6c1414c1-49fa-411b-add9-b7d7ce32ad68

**Comment by BogdanCostinas** [comment]
I believe it's  a Typo, limit the quantity not the quality


![image](https://github.com/Itheum/data-dex/assets/118804443/7b5c3d14-f1d7-467d-825f-e4a40ae7ea64)

**Comment by fuzzyduke** [comment]
Seen in Marketplace "Unlock from: 474.3 ITHEUM (17.77 USD)" takes 2 lines and pushed the preview data down causing the other elements to be pushed as well.

![image](https://github.com/Itheum/data-dex/assets/121969933/d3d7dbfc-2d7f-4a61-92ea-f1408a0cb968)

**Comment by fuzzyduke** [comment]
Wallet: Xportal

Issue while purchasing a dataset from recent Data NFTs.

Upon Acquiring a data NFT the below error is seen.

Steps to reproduce:

Browse to dashboard
Go to recent Data NFTs
Purchase the NFT at https://deploy-preview-583--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/DATANFTFT4-3ba099-2a/offer-1923
Recent Data NFTs
![image](https://github.com/Itheum/data-dex/assets/121969933/4faaeeaf-5ed7-4821-8698-cbd8d8e87074)

Comment Added:
This seems to happen in the detail page if you are clearing out the final NFTs.
For example

If there is 1 NFT left, then purchasing the NFT will result in the error.
If there are 2 NFTs left, then purchasing 1 will not throw the error as there will be a balance remaining.
